application: redlettercontent
version: 3
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: "2.6"

handlers:
- url: /favicon.ico
  static_files: static/img/favicons/favicon.ico
  upload: static/img/favicons/favicon.ico
- url: /static
  static_dir: static
- url: /js
  static_dir: static/js
- url: /img
  static_dir: static/img
- url: /css
  static_dir: static/css
- url: /.*
  script: main.application
